Bump version of gRPC again so that "bazel test ..." works again. (#80)
The error was:

```
ERROR: [...]/external/googleapis/BUILD.bazel:70:1: Generating Descriptor Set proto_library @googleapis//:_google_rpc_status_cc_proto_only failed (Exit 1) protoc failed: error executing command bazel-out/host/bin/external/com_google_protobuf/protoc '--proto_path=external/googleapis' ... (remaining 6 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
google/protobuf/any.proto: File not found.
google/rpc/status.proto: Import "google/protobuf/any.proto" was not found or had errors.
google/rpc/status.proto:91:12: "google.protobuf.Any" is not defined.
```

I think this was caused by my previous bump of the gRPC version.