Upgrade version of gRPC used to latest tag since 0.17.1 doesn't work with Bazel 0.25. (#71)
Here's the error I was getting, which is resolved with this upgrade:

ERROR: Skipping 'build/bazel/remote/execution/v2:remote_java_proto': error loading package 'build/bazel/remote/execution/v2': in <REDACTED>/external/com_github_grpc_grpc/bazel/cc_grpc_library.bzl: Label '@com_github_grpc_grpc//:bazel/generate_cc.bzl' crosses boundary of subpackage '@com_github_grpc_grpc//bazel' (perhaps you meant to put the colon here: '@com_github_grpc_grpc//bazel:generate_cc.bzl'?)